// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrcvhfIwVssgCRUQdkSgJRmC1OLpUOcJg',
    appId: '1:916684783184:web:cf206b0ee0fe96ac269b55',
    messagingSenderId: '916684783184',
    projectId: 'mytaxiadmin-a6fcf',
    authDomain: 'mytaxiadmin-a6fcf.firebaseapp.com',
    storageBucket: 'mytaxiadmin-a6fcf.appspot.com',
    measurementId: 'G-L36Y4SVJ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDta__WDxWMSl7WNxZAveacCP-_fIsIFDs',
    appId: '1:916684783184:android:645b89004faa80b8269b55',
    messagingSenderId: '916684783184',
    projectId: 'mytaxiadmin-a6fcf',
    storageBucket: 'mytaxiadmin-a6fcf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZmW7O5ZR1cb2TiLlpmH9QrRUzOVHlJw',
    appId: '1:916684783184:ios:837a8f0563c86bfa269b55',
    messagingSenderId: '916684783184',
    projectId: 'mytaxiadmin-a6fcf',
    storageBucket: 'mytaxiadmin-a6fcf.appspot.com',
    iosBundleId: 'com.ideativemind.admin',
  );
}
